# Parameterize base image components
ARG DOCKER_URL=vault.habana.ai/gaudi-docker
ARG VERSION=1.21.1
ARG BASE_NAME=ubuntu24.04
ARG PT_VERSION=2.6.0
ARG REVISION=latest
ARG REPO_TYPE=habanalabs
# Parameterize commit/branch for vllm-fork checkout
ARG VLLM_FORK_COMMIT=v0.7.2+Gaudi-1.21.0
ARG VLLM_HPU_EXTENSION_COMMIT=v1.21.0

FROM ${DOCKER_URL}/${VERSION}/${BASE_NAME}/${REPO_TYPE}/pytorch-installer-${PT_VERSION}:${REVISION}
ARG VLLM_FORK_COMMIT

ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

RUN apt update && \
    apt install -y gettext moreutils jq && \
    ln -sf /usr/bin/python3 /usr/bin/python
WORKDIR /root

# Install vllm-fork inside the container
ENV VLLM_TARGET_DEVICE=hpu
RUN git clone https://github.com/HabanaAI/vllm-fork.git && \
    cd vllm-fork && \
    git checkout ${VLLM_FORK_COMMIT} && \
    pip install -v -e .

# Install additional Python packages
RUN pip install datasets && \
    pip install pandas

# Copy utility scripts and configuration
RUN mkdir -p /root/scripts
COPY entrypoint.sh vllm_autocalc.py settings_vllm.csv template* varlist* perftest* dataset/* \
     /root/scripts
RUN chmod +x /root/scripts/*.sh

WORKDIR /root/scripts

RUN git clone https://github.com/HabanaAI/vllm-hpu-extension.git && \
    cd vllm-hpu-extension && \
    git checkout $VLLM_HPU_EXTENSION_COMMIT
    
COPY step-5-unify_measurements.py /root/scripts/vllm-hpu-extension/calibration

# Set entrypoint script
ENTRYPOINT ["/root/scripts/entrypoint.sh"]
